### ISSUE TITLE
Scalability question 

### ISSUE THREAD

**Issue by cr0hn** [Ananto30/zero#10]
Hi! Thanks for this project. It’s really nice.

I was thinking about how to scale zero services. I have some ideas, but I would like to listen to your opinions.

My first idea (and the most simple) is to use a TCP load balancer (like haproxy).

**Comment by Ananto30** [comment]
Thank you @cr0hn 

The scaling is kind of similar to other HTTP services. If you check the [Order management](https://github.com/Ananto30/zero/tree/main/examples/order_management) example, Docker is used. So we can put this in the Kubernetes cluster and do replicas. Any containerization can be used.

And the simplest one is spawn multiple servers in different ports (if on the same machine) then use a load balancer. And yes, any TCP load balancer would work.

**Comment by cr0hn** [comment]
Thx man
