### ISSUE TITLE
zmq.error.Again: Resource temporarily unavailable

### ISSUE THREAD

**Issue by ACEGuiPeng** [Ananto30/zero#11]
Hi,I'm using zeroapi in kubernates and I get an annoying issues:

![image](https://user-images.githubusercontent.com/26544186/161260574-93973158-088c-4cb9-8373-e9b110eff036.png)

And the issues happened randomly.
my zmq version is pyzmq-22.3.0.
Could you please help me how to solve my problems?

**Comment by Ananto30** [comment]
There is a timeout parameter in the client, the default is 2000ms (2s) https://github.com/Ananto30/zero/blob/main/zero/client.py#L42

If you think your program can take more time (seems like from your error), please set the timeout while creating the client like this -
```
client = ZeroClient("<HOST>", 8000, default_timeout=10000)
```

**Comment by ACEGuiPeng** [comment]
> There is a timeout parameter in the client, the default is 2000ms (2s) https://github.com/Ananto30/zero/blob/main/zero/client.py#L42
> 
> If you think your program can take more time (seems like from your error), please set the timeout while creating the client like this -
> 
> ```
> client = ZeroClient("<HOST>", 8000, default_timeout=10000)
> ```

Thanks to reply.And I had set the timeout parameter like this:
![image](https://user-images.githubusercontent.com/26544186/161886205-56278a4d-e1b3-44ef-93c8-34d6dcfe9e9d.png)

Is there another possible reason to cause this issues?

**Comment by Ananto30** [comment]
Are you facing the issue even after setting the timeout?

**Comment by ACEGuiPeng** [comment]
> Are you facing the issue even after setting the timeout?

Yes.

**Comment by Ananto30** [comment]
Add test for timeout and "Resource temporarily unavailable"

**Comment by ACEGuiPeng** [comment]
Hi,Is there something I can help to do?
By the way,my app started flask server and rpc server at the same time.May this be a reason to cause the issue?

**Comment by ACEGuiPeng** [comment]
> It would be really amazing if you can help on the above issue #12 🙏 I couldn't manage time yet.
> 
> Btw how are you running two servers at the same time? Are you using a process manager like supervisord?

Yes.I start rpc server on main thread and flask server on fork thread.

**Comment by ACEGuiPeng** [comment]
Hi,I tried this script and repeate the issue:

server code:
```
import time

from zero import ZeroServer


def echo(msg: str) -> str:
    # mock do someing
    time.sleep(5)
    return msg


if __name__ == "__main__":
    app = ZeroServer(port=5559)
    app.register_rpc(echo)
    app.run()
```
client code:
```
from zero import ZeroClient
from threading import Thread


def test(index):
    zero_client = ZeroClient("localhost", 5559, 20)
    data = zero_client.call("echo", f"{index}")
    print(data)


if __name__ == "__main__":
    # mock for multi user call,and server worker number is just 16.
    for i in range(16):
        Thread(target=test, args=(i,)).start()
```

**Comment by Ananto30** [comment]
> Yes.I start rpc server on main thread and flask server on fork thread.

Then you use the zero client inside the function of flask server?

**Comment by Ananto30** [comment]
@ACEGuiPeng any update on this? Or I will close the issue as solved.

**Comment by Ananto30** [comment]
Usually happens for timeout issues, otherwise connection issues. So I made two different ZeroExceptions - `TimeoutException` and `ConnectionException` in this pr https://github.com/Ananto30/zero/pull/29
