### ISSUE TITLE
How to specify the server's process num

### ISSUE THREAD

**Issue by nghuyong** [Ananto30/zero#16]
I want to know how to specify the server's process num when starting the server.
I will run multi-servers in one machine, but I found each server will run on all the cpus, https://github.com/Ananto30/zero/blob/main/zero/server.py#L97

**Comment by Ananto30** [comment]
Good point. You can always start another server in the same machine btw. But the performance will eventually degrade, true. That's a very good indicator to introduce process num as a param while starting the server!
