### ISSUE TITLE
Easy way to use ormsgpack as encoder

### ISSUE THREAD

**Issue by powellnorma** [Ananto30/zero#36]
By using [ormsgpack](https://pypi.org/project/ormsgpack/) as encoder, one gets the ability to serialize `datetime`, `dataclass`, etc. for free. I saw that there is a config.py, but

1. How does one (as library user) change the value of `ENCODER`? https://github.com/Ananto30/zero/blob/2a6e25a17fc434012b1b7abc1204c3f6f26d7722/zero/config.py#L11 

2. Even if the encoder supports it, dataclass is not allowed as type here:
  https://github.com/Ananto30/zero/blob/2a6e25a17fc434012b1b7abc1204c3f6f26d7722/zero/utils/type.py#L95
  One could add something like this to that function:
    ```python
    from dataclasses import is_dataclass
    if is_dataclass(return_type):
        return
    ```

**Comment by Ananto30** [comment]
You can pass the Encoder while creating the [client](https://github.com/Ananto30/zero/blob/main/zero/client_server/client.py#L19) and [server](https://github.com/Ananto30/zero/blob/main/zero/client_server/server.py#L31) 🤔

**Comment by powellnorma** [comment]
Yes, but one would first have to implement a custom class - I think making it even easier to use `ormsgpack` would be cool! Also 2. would still limit the use of dataclass

**Comment by Ananto30** [comment]
My plan is to remove these typing checks (as in specific types are allowed etc) and move that to the Encoder's responsibility and make [msgspec](https://jcristharif.com/msgspec/) as the default Encoder because it supports basic types etc.

**Comment by powellnorma** [comment]
Sounds good, it also seems to support datetime and dataclass: https://jcristharif.com/msgspec/supported-types.html
