### ISSUE TITLE
server function does not receive a typed object

### ISSUE THREAD

**Issue by foofel** [Ananto30/zero#43]
Hey, when i try to pass an object from the client to the server i get the correct data, but its not a typed object but dict, how can i change this?

**Comment by Ananto30** [comment]
My first impression was to not doing any validation on the framework itself. But as I have introduced msgspec, can use their validator function indeed. Here is the pr - https://github.com/Ananto30/zero/pull/55

**Comment by Ananto30** [comment]
Solved here https://github.com/Ananto30/zero/pull/55
