### ISSUE TITLE
Ability to surface a DNS / Name Resolution Error

### ISSUE THREAD

**Issue by surfer190** [Ananto30/zero#47]
Using the `Call the rpc methods` of the readme and changing the hostname from `localhost` to a hostname known not to resolve like: `unknownhost` results in:

    zmq.error.Again: Resource temporarily unavailable
    
    The above exception was the direct cause of the following exception:

    zero.error.ConnectionException: Connection error for recv at tcp://unknownhost:5559

Is it possible to raise a dns or name resolution error?

**Comment by Ananto30** [comment]
Sure but it will be task with not much gain :)

**Comment by surfer190** [comment]
Why? 

Thinking is a dns error would be raised immediately so workers don't have to wait for the timeout to be reached.
It would also make the error message more clear to the reader about the exact cause of the issue.

**Comment by Ananto30** [comment]
The error is pretty self-explanatory and if I think from zeromq perspective, it's not possible to avoid that timeout wait time.
