### ISSUE TITLE
Question: python version constraints

### ISSUE THREAD

**Issue by GitHK** [Ananto30/zero#6]
I see the package is currently constraint to python `>=3.9.
Being a library, I'd expect it not to have such a high requirement for python.
You do not have pinned dependencies which is great!

Dependencies python pins:
- [msgpack](https://github.com/msgpack/msgpack-python/blob/main/setup.py#L109) has no such requirement
- [zeromq](https://github.com/zeromq/pyzmq/blob/main/setup.py#L1379) is set to `>=3.6`

Any change it can be lowered to `>=3.6`? Might a PR to solve this help? I'd also add a few more git actions to build and test on separate versions of python when pushing.

Thanks for the help.

**Comment by Ananto30** [comment]
Thanks a lot @GitHK  for your question and interest! The thing is, zero supports the `async` keyword out of the box. So usually the async matured through version 3.4 to 3.7. So 3.7 is usually the last version we can support technically. And also as you mentioned we are dependant on zeromq library that requires 3.6 or +.

So I am not sure enough do we need to go lower than 3.6. Please let me know your thoughts.

(Sorry for the late reply, was on vacation.)

**Comment by GitHK** [comment]
Ops, I was meaning to say: "have the same constraint as zeromq, meaning `>=3.6` (bigger equal)".

**Comment by Ananto30** [comment]
Oh my bad. I think we can! But may be 3.7 as the async functionality got matured enough on 3.7. What do you think?

**Comment by GitHK** [comment]
If something in particular from 3.7 was used, then limiting it to 3.7 is reasonable. But if possible I'd put it to 3.6 (I would not lower it to 3.6 if changes are required).

**Comment by Ananto30** [comment]
Got you! Thanks a lot for your suggestion and concern 🙏 I will test and update that.

**Comment by Ananto30** [comment]
As we are allowing users to use dataclasses, the minimum version is 3.7 :disappointed:

**Comment by Ananto30** [comment]
Also, get_origin of typing was added on 3.8 :disappointed: https://docs.python.org/3/library/typing.html#typing.get_origin

**Comment by GitHK** [comment]
> As we are allowing users to use dataclasses, the minimum version is 3.7 😞

For dataclasses you can [use this](https://pypi.org/project/dataclasses/) for support prior to 3.6

**Comment by GitHK** [comment]
> Also, get_origin of typing was added on 3.8 😞 https://docs.python.org/3/library/typing.html#typing.get_origin

With this I am not familiar 😞

**Comment by Vortex93** [comment]
So I can not get it to work with Python 3.8 then? 😞

**Comment by Ananto30** [comment]
@Vortex93 I think it's possible to use with 3.8
I will try to test today, keep an eye for the related PR 👀
