### ISSUE TITLE
cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by IsKali-C** [Ananto30/zero#9]
client code:
![image](https://user-images.githubusercontent.com/48686680/160836608-eb058dd4-7815-4ae1-add7-8cb4630e8b83.png)

server code:
![image](https://user-images.githubusercontent.com/48686680/160837908-dbad6c21-e0a3-40ce-b597-8ca242f7caa5.png)
![image](https://user-images.githubusercontent.com/48686680/160838117-0763bd12-d8cb-490f-9e40-f8d2751f1c70.png)

after called，error coming:
![image](https://user-images.githubusercontent.com/48686680/160839188-a2aa34ca-5c93-41eb-aa10-b0a55b28ae24.png)

who miss this? what happened?
somebody help me out,please! Thanks a lot.

**Comment by Ananto30** [comment]
Interesting. This error only happens when this happens -
```
status_code, webhooks = None
```
But you are handling errors and in your case, worst case would be `status_code, webhooks = None, None`

Would you please share the decorator you are using on the `receive_webhook_list` function?

And you can debug easily by just catching the output like this - 
```
check = zero_client.call("call_receive_webhook_list", args)
print(check)  # or debug check
```

**Comment by IsKali-C** [comment]
> Interesting. This error only happens when this happens -
> 
> ```
> status_code, webhooks = None
> ```
> 
> But you are handling errors and in your case, worst case would be `status_code, webhooks = None, None`
> 
> Would you please share the decorator you are using on the `receive_webhook_list` function?
> 
> And you can debug easily by just catching the output like this -
> 
> ```
> check = zero_client.call("call_receive_webhook_list", args)
> print(check)  # or debug check
> ```

**Comment by IsKali-C** [comment]
> Interesting. This error only happens when this happens -
> 
> ```
> status_code, webhooks = None
> ```
> 
> But you are handling errors and in your case, worst case would be `status_code, webhooks = None, None`
> 
> Would you please share the decorator you are using on the `receive_webhook_list` function?
> 
> And you can debug easily by just catching the output like this -
> 
> ```
> check = zero_client.call("call_receive_webhook_list", args)
> print(check)  # or debug check
> ```

How stupid I am...
You are absolutely right！
is decorator problem.
thanks!
